apiVersion: v1
kind: Pod
metadata:
  name: spacetime
  labels:
    app: spacetime
spec:
  containers:
  - name: spacetime
    image: clockworklabs/spacetimedb
    command: ["/bin/sh"]
    args: ["-c", "spacetimedb start"] #--listen-addr=0.0.0.0.3000"]
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spacetime
spec:
  selector:
    app: spacetime
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80